import { MarketResearchReport } from '../types';

export function generateClientMarketData(niche: string): MarketResearchReport {
  const cleanNiche = niche?.trim() || 'Servicios y Productos Especializados';
  const cleanNicheSlug = cleanNiche.toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 10) || 'market';

  return {
    niche: cleanNiche,
    analyzedAt: new Date().toISOString(),
    summary: `Investigación competitiva en tiempo real sobre "${cleanNiche}". El mercado presenta una intensa actividad en canales de adquisición digital, con competidores compitiendo fuertemente en Google Search por términos de alta intención y Meta Ads (formatos de video UGC y prueba social directa).`,
    metrics: {
      niche: cleanNiche,
      totalMarketSizeEst: '$3.4B USD (Global) / $380M (Hispanoamérica)',
      growthRateAnnual: '+19.8% CAGR',
      saturationLevel: 'Media (Crecimiento)',
      averageCpcNiche: '$2.20 - $5.40 USD',
      topConvertingAdHook: `La solución integral para optimizar ${cleanNiche} sin fricción`,
      untappedOpportunity: 'Implementación guiada con onboarding autónomo y soporte 24/7 en español',
      priceElasticity: 'Media',
    },
    competitors: [
      {
        id: 'comp-1',
        name: `Líder Prime ${cleanNiche}`,
        website: `${cleanNicheSlug}-prime.com`,
        tagline: `La plataforma líder y referente de la industria en ${cleanNiche}`,
        marketSharePercent: 35,
        monthlyTrafficEst: '340K visitas/mes',
        pricingModel: 'Planes escalables desde $49/mes',
        avgPricePoint: '$89/mes',
        positioning: 'Líder consolidado con mayor reconocimiento de marca en el sector',
        targetAudience: 'Empresas medianas y grandes buscando estabilidad y soporte corporativo',
        techStack: ['React', 'Node.js', 'AWS', 'Segment', 'Hubspot', 'Stripe'],
        strengths: ['Marca establecida con alto volumen de búsqueda', 'Ecosistema amplio de integraciones', 'Soporte multicanal'],
        vulnerabilities: ['Precios elevados para principiantes', 'Soporte prioritario solo para cuentas grandes'],
        organicKeywordsRanked: 12500,
        paidSearchSharePercent: 38,
        metaAdActiveCount: 26,
        adVelocityScore: 86,
        recentStrategicMove: 'Incremento de puja en Google Ads para defender términos de marca',
      },
      {
        id: 'comp-2',
        name: `Nova ${cleanNiche} Ágil`,
        website: `nova-${cleanNicheSlug}.io`,
        tagline: `Soluciones modernas, rápidas y accesibles para ${cleanNiche}`,
        marketSharePercent: 27,
        monthlyTrafficEst: '210K visitas/mes',
        pricingModel: 'Suscripción directa $29 - $99/mes',
        avgPricePoint: '$49/mes',
        positioning: 'Alternativa ágil de nueva generación y menor costo',
        targetAudience: 'Emprendedores, pequeñas empresas y equipos independientes',
        techStack: ['Next.js', 'PostgreSQL', 'Tailwind', 'Stripe', 'PostHog'],
        strengths: ['Experiencia de usuario moderna', 'Onboarding en minutos', 'Precio competitivo'],
        vulnerabilities: ['Menor cantidad de integraciones enterprise', 'Poca presencia en licitaciones corporativas'],
        organicKeywordsRanked: 7800,
        paidSearchSharePercent: 32,
        metaAdActiveCount: 30,
        adVelocityScore: 92,
        recentStrategicMove: 'Lanzamiento de campaña comparativa directa en Google Search y Meta Ads',
      },
      {
        id: 'comp-3',
        name: `Expert Enterprise ${cleanNiche}`,
        website: `expert-${cleanNicheSlug}.com`,
        tagline: 'Seguridad y personalización de alto nivel para grandes cuentas',
        marketSharePercent: 20,
        monthlyTrafficEst: '150K visitas/mes',
        pricingModel: 'Cotización a medida (desde $290/mes)',
        avgPricePoint: '$350/mes',
        positioning: 'Especialista en proyectos a medida y alta personalización',
        targetAudience: 'Grandes instituciones y corporativos',
        techStack: ['Java Spring', 'Angular', 'Cloudflare', 'Oracle'],
        strengths: ['Cumplimiento de normativas de seguridad', 'Contratos SLA dedicados'],
        vulnerabilities: ['Ventas lentas con demos obligatorias', 'Cero transparencia de precios online'],
        organicKeywordsRanked: 8900,
        paidSearchSharePercent: 18,
        metaAdActiveCount: 12,
        adVelocityScore: 55,
        recentStrategicMove: 'Enfoque en prospección B2B en LinkedIn y eventos de la industria',
      }
    ],
    googleAds: [
      {
        id: 'g-ad-1',
        competitorName: `Nova ${cleanNiche} Ágil`,
        adType: 'Search',
        headline: `¿Buscando la mejor opción en ${cleanNiche}? | Prueba Nova`,
        displayUrl: `nova-${cleanNicheSlug}.io/comparativa`,
        description: `Descubre por qué cientos de clientes eligen nuestra plataforma de ${cleanNiche}. Rápido, seguro y al mejor precio. Prueba gratuita.`,
        sitelinks: ['Ver Planes y Precios', 'Casos de Éxito', 'Tour de Producto', 'Contacto'],
        targetedKeywords: [`mejor ${cleanNiche}`, `${cleanNiche} precios`, `proveedores de ${cleanNiche}`],
        intentLevel: 'Alta Intención de Compra',
        psychologicalHook: 'Velocidad de implementación + Fricción cero de inicio',
        landingPageAngle: 'Página de aterrizaje optimizada para conversión rápida con prueba gratis.',
        estimatedCpcRange: '$2.40 - $4.80 USD',
        whyItWorks: 'Captura al usuario en el momento exacto de comparación activa.',
      },
      {
        id: 'g-ad-2',
        competitorName: `Líder Prime ${cleanNiche}`,
        adType: 'Search',
        headline: `La Solución Oficial de ${cleanNiche} #1 | Calidad Garantizada`,
        displayUrl: `${cleanNicheSlug}-prime.com/lider`,
        description: `Más de 10,000 clientes confían en nuestra infraestructura para ${cleanNiche}. Solicita asesoría hoy mismo.`,
        sitelinks: ['Empieza Hoy', 'Soluciones', 'Opiniones', 'Agenda Asesoría'],
        targetedKeywords: [`servicio ${cleanNiche}`, `empresa ${cleanNiche}`, `software ${cleanNiche}`],
        intentLevel: 'Comparativa / Solución',
        psychologicalHook: 'Prueba social masiva y autoridad en la industria',
        landingPageAngle: 'Landing corporativa con testimonios y sellos de garantía.',
        estimatedCpcRange: '$3.50 - $6.20 USD',
        whyItWorks: 'Defiende su liderazgo capturando búsquedas con alta prueba social.',
      }
    ],
    metaAds: [
      {
        id: 'm-ad-1',
        competitorName: `Nova ${cleanNiche} Ágil`,
        platform: ['Instagram', 'Facebook'],
        format: 'Video UGC',
        hookText: `“Si trabajas en ${cleanNiche}, tienes que ver cómo resolvimos este problema en 2 minutos...”`,
        bodyCopy: `Deja de perder tiempo en procesos manuales y desordenados en ${cleanNiche}. Conoce la herramienta que está transformando el sector. 👉 Haz clic para empezar gratis.`,
        callToAction: 'Probar Gratis',
        targetPersona: 'Profesionales y directores de área buscando optimizar tiempo',
        emotionalTrigger: 'Dolor / Agitación',
        estimatedActiveDays: 35,
        spendTier: 'Medio ($500-$3K/m)',
        whyItWorks: 'Formato dinámico estilo selfie que genera conexión inmediata y alta retención.',
        funnelStage: 'TOFU (Atracción)',
        adLibrarySearchQuery: `Nova ${cleanNiche}`,
      },
      {
        id: 'm-ad-2',
        competitorName: `Líder Prime ${cleanNiche}`,
        platform: ['Instagram', 'Facebook'],
        format: 'Carrusel',
        hookText: `3 claves fundamentales para dominar y escalar en ${cleanNiche} este año`,
        bodyCopy: `Slide 1: Automatiza tareas repetitivas. Slide 2: Centraliza tus datos en un solo lugar. Slide 3: Descarga la guía definitiva para ${cleanNiche}.`,
        callToAction: 'Descargar Guía',
        targetPersona: 'Dueños de negocio y tomadores de decisión',
        emotionalTrigger: 'Autoridad / Caso de Éxito',
        estimatedActiveDays: 52,
        spendTier: 'Agresivo ($3K-$15K/m)',
        whyItWorks: 'Lead magnet educacional que captura prospectos cualificados.',
        funnelStage: 'MOFU (Consideración)',
        adLibrarySearchQuery: `Prime ${cleanNiche}`,
      }
    ],
    googleMapsLocations: [
      {
        id: 'loc-1',
        competitorId: 'comp-1',
        competitorName: `Líder Prime ${cleanNiche}`,
        title: `Líder Prime HQ - Centro Corporativo`,
        lat: 19.4326,
        lng: -99.1925,
        address: 'Av. Paseo de la Reforma 222, Cuauhtémoc, Ciudad de México, CDMX',
        city: 'Ciudad de México',
        country: 'México',
        rating: 4.8,
        userRatingCount: 165,
        priceLevel: '$$$',
        placeId: 'ChIJN1t_tDeuEmsRUsoyG83frY4',
        googleMapsUri: `https://www.google.com/maps/search/?api=1&query=Lider+Prime+CDMX`,
        localCoverageType: 'Headquarters',
        sentimentSummary: 'Alta reputación por atención profesional y capacitaciones.',
      },
      {
        id: 'loc-2',
        competitorId: 'comp-2',
        competitorName: `Nova ${cleanNiche} Ágil`,
        title: `Nova Innovation Hub - Financial District`,
        lat: 25.7617,
        lng: -80.1918,
        address: '1200 Brickell Ave, Miami, FL 33131, EE. UU.',
        city: 'Miami',
        country: 'Estados Unidos',
        rating: 4.9,
        userRatingCount: 210,
        priceLevel: '$$',
        placeId: 'ChIJR2t1g0O32YgR638v0h1k9vQ',
        googleMapsUri: `https://www.google.com/maps/search/?api=1&query=Nova+Miami`,
        localCoverageType: 'Headquarters',
        sentimentSummary: 'Reseñas destacando soporte ágil y modernidad en sus servicios.',
      }
    ],
    googleSearchResults: [
      {
        id: 'serp-1',
        competitorName: `Líder Prime ${cleanNiche}`,
        rankPosition: 1,
        pageTitle: `Servicios Líderes en ${cleanNiche} | Web Oficial`,
        snippet: `Descubre por qué las empresas líderes eligen nuestras soluciones para ${cleanNiche}. Asesoría experta y resultados garantizados.`,
        url: `https://${cleanNicheSlug}-prime.com`,
        searchQuery: `mejores opciones ${cleanNiche}`,
        monthlySearchVolumeEst: '15,200 búsquedas/mes',
        serpFeatures: ['Featured Snippet', 'SiteLinks'],
        intent: 'Transaccional',
        domainAuthority: 81,
      },
      {
        id: 'serp-2',
        competitorName: `Nova ${cleanNiche} Ágil`,
        rankPosition: 2,
        pageTitle: `Nova: La Alternativa Moderna para ${cleanNiche}`,
        snippet: `Optimiza tu operación en ${cleanNiche} con tarifas justas y sin complicaciones. Empieza hoy mismo con prueba sin costo.`,
        url: `https://nova-${cleanNicheSlug}.io`,
        searchQuery: `servicios de ${cleanNiche}`,
        monthlySearchVolumeEst: '9,800 búsquedas/mes',
        serpFeatures: ['SiteLinks', 'People Also Ask'],
        intent: 'Comercial',
        domainAuthority: 73,
      }
    ],
    predictions: [
      {
        id: 'pred-1',
        title: `Adopción de IA y Automatizaciones en ${cleanNiche}`,
        category: 'Innovación Tecnológica',
        confidenceScore: 93,
        forecastTimeframe: '60 días',
        predictedImpact: 'Crítico',
        description: `Los proveedores en ${cleanNiche} que integren herramientas asistidas por IA capturarán hasta un 40% más de demanda frente a opciones estáticas.`,
        leadingIndicator: 'Crecimiento del 190% en búsquedas de automatización en los últimos meses.',
        recommendedAction: 'Desplegar soluciones con procesos autónomos y demos interactivas.',
        growthRatePct: 175,
      },
      {
        id: 'pred-2',
        title: 'Presión Competitiva en Precios y Ofertas de Entrada',
        category: 'Guerra de Precios',
        confidenceScore: 86,
        forecastTimeframe: '90 días',
        predictedImpact: 'Alto',
        description: 'La llegada de nuevas alternativas forzará a ofrecer pruebas sin compromiso y mayores garantías.',
        leadingIndicator: 'Aumento de ofertas promocionales en competidores emergentes.',
        recommendedAction: 'Diferenciarse por calidad de soporte y velocidad de respuesta.',
        growthRatePct: 50,
      }
    ],
    alerts: [
      {
        id: 'alt-1',
        timestamp: 'Hace unos minutos',
        type: 'ad_shift',
        title: `Nuevas campañas activas detectadas en ${cleanNiche}`,
        sourceCompetitor: `Nova ${cleanNiche} Ágil`,
        message: 'Incremento de pauta en anuncios de video destacando ventajas de costo y rapidez.',
        severity: 'high',
        suggestedReaction: 'Activar campañas en Google Search en términos comparativos.',
        isRead: false,
      }
    ],
    chartData: [
      { competitor: `Líder Prime ${cleanNiche}`, marketShare: 35, adSpendScore: 86, featureSophistication: 90, priceIndex: 85, organicStrength: 88, sentimentScore: 79 },
      { competitor: `Nova ${cleanNiche} Ágil`, marketShare: 27, adSpendScore: 92, featureSophistication: 80, priceIndex: 55, organicStrength: 73, sentimentScore: 90 },
      { competitor: `Expert Enterprise ${cleanNiche}`, marketShare: 20, adSpendScore: 55, featureSophistication: 88, priceIndex: 95, organicStrength: 82, sentimentScore: 68 },
    ],
    trendHistory: [
      { month: 'Mes -4', 'Demanda': 35, 'Tendencia IA': 40 },
      { month: 'Mes -3', 'Demanda': 48, 'Tendencia IA': 58 },
      { month: 'Mes -2', 'Demanda': 62, 'Tendencia IA': 75 },
      { month: 'Mes -1', 'Demanda': 80, 'Tendencia IA': 90 },
      { month: 'Actual', 'Demanda': 95, 'Tendencia IA': 100 },
      { month: '+30d Proy.', 'Demanda': 115, 'Tendencia IA': 130 },
      { month: '+60d Proy.', 'Demanda': 140, 'Tendencia IA': 160 },
    ],
    unclaimedBlueOceans: [
      {
        gap: `Onboarding guiado y configuración en 2 minutos para ${cleanNiche}`,
        whyMissing: 'Los competidores tradicionales exigen largos formularios o llamadas de ventas.',
        howToCapitalize: 'Permitir al usuario probar y activar el servicio en 1 solo clic.',
      },
      {
        gap: 'Transparencia radical de tarifas sin costos ocultos',
        whyMissing: 'La mayoría de competidores oculta precios o cobra extras por funciones básicas.',
        howToCapitalize: 'Promover un modelo de precios claros, directos y con garantía.',
      }
    ],
    strategicPlaybook: [
      {
        phase: 'Fase 1: Captura de Demanda en Búsqueda (Días 1-15)',
        action: 'Desplegar anuncios en Google Search en keywords de alta intención transaccional.',
        targetCompetitor: 'Competidores líderes del nicho',
        expectedROI: '3.5x ROAS inicial',
      },
      {
        phase: 'Fase 2: Dominio en Meta Ads con Video UGC (Días 15-30)',
        action: 'Publicar testimoniales y demostraciones de producto resolviendo el dolor principal.',
        targetCompetitor: 'Todo el sector',
        expectedROI: '+40% incremento en clics y conversiones',
      }
    ]
  };
}
