import { MarketResearchReport } from '../types';

export function generateClientMarketData(niche: string): MarketResearchReport {
  const cleanNiche = niche?.trim() || 'Servicios y Software B2B';

  return {
    niche: cleanNiche,
    analyzedAt: new Date().toISOString(),
    summary: `Diagnóstico de inteligencia competitiva para "${cleanNiche}". Mercado caracterizado por una fuerte migración hacia procesos automatizados y soluciones ágiles. La competencia en pauta digital se concentra fuertemente en Meta Ads (formatos de video UGC con ángulos de alivio de carga operativa) y Google Ads (búsquedas transaccionales de alta intención y comparativas entre software líderes).`,
    metrics: {
      niche: cleanNiche,
      totalMarketSizeEst: '$3.8B USD (Global) / $420M (LATAM & España)',
      growthRateAnnual: '+21.8% CAGR',
      saturationLevel: 'Media (Crecimiento)',
      averageCpcNiche: '$2.40 - $5.80 USD',
      topConvertingAdHook: `Automatiza el 80% de tus operaciones en ${cleanNiche} sin contratar más personal`,
      untappedOpportunity: 'Implementación guiada con onboarding autónomo en menos de 3 minutos',
      priceElasticity: 'Media',
    },
    competitors: [
      {
        id: 'comp-1',
        name: 'ApexFlow Growth',
        website: 'apexflow.io',
        tagline: `La solución líder todo-en-uno para escalar en ${cleanNiche}`,
        marketSharePercent: 36,
        monthlyTrafficEst: '480K visitas/mes',
        pricingModel: 'Freemium + Planes desde $49/mes',
        avgPricePoint: '$89/mes',
        positioning: 'Líder corporativo consolidado con alto reconocimiento de marca',
        targetAudience: 'Directores de Operaciones y Gerentes de Área',
        techStack: ['React', 'Node.js', 'AWS', 'Segment', 'Hubspot', 'Stripe'],
        strengths: ['Marca establecida con alto reconocimiento', 'Ecosistema de integraciones masivo', 'Soporte 24/7 en español'],
        vulnerabilities: ['Curva de aprendizaje empinada', 'Precios que escalan exponencialmente con usuarios extra', 'Soporte lento para cuentas medianas'],
        organicKeywordsRanked: 14200,
        paidSearchSharePercent: 42,
        metaAdActiveCount: 28,
        adVelocityScore: 88,
        recentStrategicMove: 'Lanzamiento de módulo de IA predictiva con sobrecosto del 30%',
      },
      {
        id: 'comp-2',
        name: 'NovaPulse Ágil',
        website: 'novapulse.co',
        tagline: `Automatización moderna y veloz para equipos en ${cleanNiche}`,
        marketSharePercent: 28,
        monthlyTrafficEst: '310K visitas/mes',
        pricingModel: 'Suscripción directa $29 - $129/mes',
        avgPricePoint: '$59/mes',
        positioning: 'Alternativa rápida, moderna y económica a los software tradicionales',
        targetAudience: 'Startups, agencias y medianos empresarios independientes',
        techStack: ['Next.js', 'PostgreSQL', 'Tailwind', 'Stripe', 'PostHog'],
        strengths: ['UI/UX minimalista y ultra veloz', 'Onboarding en 2 minutos', 'Precio altamente competitivo'],
        vulnerabilities: ['Pocas opciones para flujos ultra complejos', 'Falta de certificaciones enterprise SOC2'],
        organicKeywordsRanked: 9400,
        paidSearchSharePercent: 33,
        metaAdActiveCount: 36,
        adVelocityScore: 94,
        recentStrategicMove: 'Campaña agresiva de comparativa directa "Vs ApexFlow" en Google Search',
      },
      {
        id: 'comp-3',
        name: 'OmniScale Enterprise',
        website: 'omniscale.com',
        tagline: 'Seguridad de grado bancario y control total para grandes corporaciones',
        marketSharePercent: 20,
        monthlyTrafficEst: '190K visitas/mes',
        pricingModel: 'Cotización Enterprise (desde $350/mes)',
        avgPricePoint: '$450/mes',
        positioning: 'Solución Enterprise de alta seguridad y personalización a medida',
        targetAudience: 'Grandes instituciones con normativas de seguridad estrictas',
        techStack: ['Java Spring', 'Angular', 'Oracle Cloud', 'Datadog'],
        strengths: ['Cumplimiento HIPAA / GDPR estricto', 'Acuerdos SLA garantizados del 99.99%'],
        vulnerabilities: ['Ventas lentas con demos obligatorias', 'Interfaz visual anticuada', 'Cero transparencia en precios online'],
        organicKeywordsRanked: 11500,
        paidSearchSharePercent: 15,
        metaAdActiveCount: 8,
        adVelocityScore: 45,
        recentStrategicMove: 'Retiro de anuncios de Meta para concentrarse en LinkedIn Ads y eventos presenciales',
      },
      {
        id: 'comp-4',
        name: 'KlaroLite Simple',
        website: 'klarolite.app',
        tagline: 'Simple, sin complicaciones ni contratos forzosos',
        marketSharePercent: 16,
        monthlyTrafficEst: '125K visitas/mes',
        pricingModel: 'Pay-as-you-go desde $9/mes',
        avgPricePoint: '$19/mes',
        positioning: 'La opción de bajo costo para freelancers y micro-negocios',
        targetAudience: 'Solopreneurs y negocios en etapa temprana',
        techStack: ['Vue.js', 'Supabase', 'Cloudflare Workers'],
        strengths: ['Sin compromiso mensual', 'Muy fácil de probar sin tarjeta de crédito'],
        vulnerabilities: ['Baja retención de clientes a largo plazo', 'Sin soporte personalizado'],
        organicKeywordsRanked: 4600,
        paidSearchSharePercent: 10,
        metaAdActiveCount: 18,
        adVelocityScore: 72,
        recentStrategicMove: 'Descuento agresivo del 50% anual para retener suscriptores',
      }
    ],
    googleAds: [
      {
        id: 'g-ad-1',
        competitorName: 'NovaPulse Ágil',
        adType: 'Search',
        headline: `¿Cansado de software lento en ${cleanNiche}? | Prueba NovaPulse`,
        displayUrl: 'novapulse.co/migracion-rapida',
        description: 'Migra tus datos en 5 minutos sin perder historial. Interfaz 3x más rápida y ahorra un 45% cada mes. Sin tarjeta requerida.',
        sitelinks: ['Ver Comparativa de Precios', 'Calculadora de Ahorro', 'Casos de Éxito', 'Demo Interactivo'],
        targetedKeywords: [`alternativa apexflow`, `software ${cleanNiche} economico`, `mejor herramienta ${cleanNiche}`],
        intentLevel: 'Comparativa / Solución',
        psychologicalHook: 'Frustración con el software actual + Fricción cero de cambio',
        landingPageAngle: 'Página de comparación directa destacando ventajas de velocidad y tabla de precios.',
        estimatedCpcRange: '$3.20 - $5.10 USD',
        whyItWorks: 'Ataca directamente a usuarios insatisfechos del líder en el momento exacto de búsqueda.',
      },
      {
        id: 'g-ad-2',
        competitorName: 'ApexFlow Growth',
        adType: 'Search',
        headline: `El Software #1 de ${cleanNiche} | Certificado y Seguro`,
        displayUrl: 'apexflow.io/lider-industria',
        description: 'Más de 15,000 negocios confían en nuestra infraestructura. Automatiza tus procesos hoy con prueba gratuita de 14 días.',
        sitelinks: ['Empieza Gratis Hoy', 'Tour de Producto', 'Agenda Demo', 'Precios y Planes'],
        targetedKeywords: [`${cleanNiche} software`, `plataforma ${cleanNiche}`, `sistema gestion ${cleanNiche}`],
        intentLevel: 'Alta Intención de Compra',
        psychologicalHook: 'Seguridad por número de clientes (Prueba Social) y Autoridad absoluta',
        landingPageAngle: 'Landing corporativa con testimonios en video de marcas reconocidas.',
        estimatedCpcRange: '$4.50 - $6.90 USD',
        whyItWorks: 'Defiende su liderazgo capturando búsquedas genéricas con prueba social abrumadora.',
      },
      {
        id: 'g-ad-3',
        competitorName: 'KlaroLite Simple',
        adType: 'Search',
        headline: `${cleanNiche} Simple desde $9/mes | Sin Contratos`,
        displayUrl: 'klarolite.app/precios-claros',
        description: 'No pagues por funciones que no usas. Configura tu cuenta en 60 segundos y empieza a operar hoy mismo.',
        sitelinks: ['Plan Gratuito 30 días', 'Precios Claros', 'Plantillas Listas', 'Guía Rápida'],
        targetedKeywords: [`${cleanNiche} barato`, `software ${cleanNiche} facil`, `app ${cleanNiche} principiantes`],
        intentLevel: 'Educacional / TOFU',
        psychologicalHook: 'Aversión a la pérdida y simplicidad sin riesgo financiero',
        landingPageAngle: 'Landing ultra minimalista con botón de registro con Google en 1 clic.',
        estimatedCpcRange: '$1.80 - $2.90 USD',
        whyItWorks: 'Atrae a clientes de bajo presupuesto que descartan a los competidores caros.',
      }
    ],
    metaAds: [
      {
        id: 'm-ad-1',
        competitorName: 'NovaPulse Ágil',
        platform: ['Instagram', 'Facebook', 'Messenger'],
        format: 'Video UGC',
        hookText: `“Estaba a punto de renunciar por el desorden en mi gestión de ${cleanNiche}, hasta que probé esto...”`,
        bodyCopy: `La mayoría de herramientas en ${cleanNiche} son demasiado complejas o cuestan una fortuna. NovaPulse resolvió mi flujo de trabajo en 20 minutos. 👉 Toca el enlace y pruébalo gratis.`,
        callToAction: 'Probar Gratis Ahora',
        targetPersona: 'Emprendedores y fundadores abrumados por la carga operativa',
        emotionalTrigger: 'Dolor / Agitación',
        estimatedActiveDays: 42,
        spendTier: 'Agresivo ($3K-$15K/m)',
        whyItWorks: 'El formato UGC selfie parece contenido orgánico de un colega, lo que genera 3.4x mayor retención.',
        funnelStage: 'TOFU (Atracción)',
        adLibrarySearchQuery: `NovaPulse ${cleanNiche}`,
      },
      {
        id: 'm-ad-2',
        competitorName: 'ApexFlow Growth',
        platform: ['Instagram', 'Facebook'],
        format: 'Carrusel',
        hookText: `5 errores fatales que cometen los negocios en ${cleanNiche} (y cómo evitarlos)`,
        bodyCopy: 'Slide 1: No automatizar el seguimiento. Slide 2: Datos dispersos en hojas de cálculo. Descarga la plantilla oficial que usan los líderes de la industria.',
        callToAction: 'Descargar Guía Gratuita',
        targetPersona: 'Gerentes de área que buscan optimización y mejores prácticas',
        emotionalTrigger: 'Autoridad / Caso de Éxito',
        estimatedActiveDays: 68,
        spendTier: 'Escala Masiva (+$15K/m)',
        whyItWorks: 'Lead magnet educacional de alto valor que construye base de datos cualificada para retargeting.',
        funnelStage: 'MOFU (Consideración)',
        adLibrarySearchQuery: `ApexFlow ${cleanNiche}`,
      },
      {
        id: 'm-ad-3',
        competitorName: 'NovaPulse Ágil',
        platform: ['Instagram', 'Facebook'],
        format: 'Fundador / Storytelling',
        hookText: '“Creamos esta herramienta porque estábamos hartos de pagar $500/mes a software que se congelaba.”',
        bodyCopy: 'Construimos lo que nosotros mismos necesitábamos: rápido, confiable y a un precio honesto. Si tienes más de 10 clientes, esto cambiará tu semana.',
        callToAction: 'Empezar en 2 Minutos',
        targetPersona: 'Dueños de negocio con sesgo anti-corporativo',
        emotionalTrigger: 'Prueba Social Masiva',
        estimatedActiveDays: 24,
        spendTier: 'Medio ($500-$3K/m)',
        whyItWorks: 'Conecta emocionalmente mediante la empatía del fundador y ataca la desconfianza.',
        funnelStage: 'BOFU (Conversión Directa)',
        adLibrarySearchQuery: `NovaPulse ${cleanNiche}`,
      }
    ],
    googleMapsLocations: [
      {
        id: 'loc-1',
        competitorId: 'comp-1',
        competitorName: 'ApexFlow Growth',
        title: 'ApexFlow Global HQ - Polanco Innovation Center',
        lat: 19.4326,
        lng: -99.1925,
        address: 'Campos Elíseos 204, Polanco V Secc, Miguel Hidalgo, 11560 Ciudad de México, CDMX',
        city: 'Ciudad de México',
        country: 'México',
        rating: 4.7,
        userRatingCount: 184,
        priceLevel: '$$$',
        placeId: 'ChIJN1t_tDeuEmsRUsoyG83frY4',
        googleMapsUri: `https://www.google.com/maps/search/?api=1&query=ApexFlow+CDMX`,
        localCoverageType: 'Headquarters',
        sentimentSummary: 'Elogios por capacitaciones presenciales; críticas aisladas por tiempos de espera.',
      },
      {
        id: 'loc-2',
        competitorId: 'comp-2',
        competitorName: 'NovaPulse Ágil',
        title: 'NovaPulse Innovation Studio - Brickell Financial',
        lat: 25.7617,
        lng: -80.1918,
        address: '1200 Brickell Ave, Miami, FL 33131, EE. UU.',
        city: 'Miami',
        country: 'Estados Unidos',
        rating: 4.9,
        userRatingCount: 236,
        priceLevel: '$$',
        placeId: 'ChIJR2t1g0O32YgR638v0h1k9vQ',
        googleMapsUri: `https://www.google.com/maps/search/?api=1&query=NovaPulse+Miami`,
        localCoverageType: 'Headquarters',
        sentimentSummary: 'Reseñas 5 estrellas destacando la velocidad de soporte y modernidad de sus oficinas.',
      },
      {
        id: 'loc-3',
        competitorId: 'comp-2',
        competitorName: 'NovaPulse Ágil',
        title: 'NovaPulse Hub Andino - El Poblado',
        lat: 6.2088,
        lng: -75.5678,
        address: 'Cra. 43A #1-50, El Poblado, Medellín, Antioquia, Colombia',
        city: 'Medellín',
        country: 'Colombia',
        rating: 4.8,
        userRatingCount: 94,
        priceLevel: '$$',
        placeId: 'ChIJwW8lO24mRI4RskN9M2mN7gI',
        googleMapsUri: `https://www.google.com/maps/search/?api=1&query=NovaPulse+Medellin`,
        localCoverageType: 'Regional Hub',
        sentimentSummary: 'Centro neurálgico de soporte para Latinoamérica con altísima satisfacción.',
      },
      {
        id: 'loc-4',
        competitorId: 'comp-3',
        competitorName: 'OmniScale Enterprise',
        title: 'OmniScale Enterprise Center - Paseo de la Castellana',
        lat: 40.4531,
        lng: -3.6883,
        address: 'Paseo de la Castellana 110, Chamartín, 28046 Madrid, España',
        city: 'Madrid',
        country: 'España',
        rating: 4.6,
        userRatingCount: 88,
        priceLevel: '$$$$',
        placeId: 'ChIJgTwKgJcpQg0RaJQN4STslMo',
        googleMapsUri: `https://www.google.com/maps/search/?api=1&query=OmniScale+Madrid`,
        localCoverageType: 'Regional Hub',
        sentimentSummary: 'Alta reputación en consultoría de seguridad y cumplimiento para la UE.',
      }
    ],
    googleSearchResults: [
      {
        id: 'serp-1',
        competitorName: 'ApexFlow Growth',
        rankPosition: 1,
        pageTitle: `El Software Líder de ${cleanNiche} en 2026 | ApexFlow Oficial`,
        snippet: `Descubre por qué más de 15,000 empresas eligen ApexFlow para gestionar y automatizar ${cleanNiche}. Prueba gratis 14 días con soporte 24/7 en español.`,
        url: 'https://apexflow.io/plataforma-lider',
        searchQuery: `mejor software ${cleanNiche}`,
        monthlySearchVolumeEst: '18,500 búsquedas/mes',
        serpFeatures: ['Featured Snippet', 'SiteLinks'],
        intent: 'Transaccional',
        domainAuthority: 82,
      },
      {
        id: 'serp-2',
        competitorName: 'NovaPulse Ágil',
        rankPosition: 2,
        pageTitle: `NovaPulse: Automatización Ágil para ${cleanNiche} | 3x Más Rápido`,
        snippet: `Ahorra hasta 12 horas a la semana con la interfaz moderna de NovaPulse. Sin contratos forzosos ni configuraciones complejas. Comienza en 2 minutos.`,
        url: 'https://novapulse.co/soluciones',
        searchQuery: `herramientas automatizadas ${cleanNiche}`,
        monthlySearchVolumeEst: '12,200 búsquedas/mes',
        serpFeatures: ['SiteLinks', 'People Also Ask'],
        intent: 'Comercial',
        domainAuthority: 74,
      },
      {
        id: 'serp-3',
        competitorName: 'OmniScale Enterprise',
        rankPosition: 3,
        pageTitle: `OmniScale Enterprise: Seguridad y Cumplimiento para ${cleanNiche}`,
        snippet: `Infraestructura certificada HIPAA, SOC2 y GDPR para grandes instituciones. Solicita una demostración guiada con nuestros arquitectos de soluciones.`,
        url: 'https://omniscale.com/enterprise',
        searchQuery: `software enterprise ${cleanNiche}`,
        monthlySearchVolumeEst: '4,100 búsquedas/mes',
        serpFeatures: ['SiteLinks'],
        intent: 'Transaccional',
        domainAuthority: 79,
      }
    ],
    predictions: [
      {
        id: 'pred-1',
        title: 'Adopción Masiva de Automatizaciones con Agentes de IA en Tiempo Real',
        category: 'Innovación Tecnológica',
        confidenceScore: 94,
        forecastTimeframe: '60 días',
        predictedImpact: 'Crítico',
        description: `La demanda de automatización con agentes autónomos en ${cleanNiche} crecerá un 180%. Las herramientas estáticas perderán hasta 35% de cuota.`,
        leadingIndicator: 'Incremento del 210% en búsquedas de "automatización con IA" en los últimos 45 días.',
        recommendedAction: 'Lanzar un feature insignia de IA con demo interactiva antes de que los líderes lo monopolicen.',
        growthRatePct: 180,
      },
      {
        id: 'pred-2',
        title: 'Guerra de Precios en Planes de Entrada y Mayor Presión en CAC',
        category: 'Guerra de Precios',
        confidenceScore: 88,
        forecastTimeframe: '90 días',
        predictedImpact: 'Alto',
        description: 'La proliferación de competidores de bajo costo forzará a ofrecer pruebas gratuitas sin tarjeta y garantías ampliadas.',
        leadingIndicator: 'Descuentos promocionales del 50% en competidores como KlaroLite.',
        recommendedAction: 'Competir por valor, soporte humano en español y velocidad de implementación en lugar de bajar precios.',
        growthRatePct: 45,
      }
    ],
    alerts: [
      {
        id: 'alt-1',
        timestamp: 'Hace 4 minutos',
        type: 'ad_shift',
        title: `NovaPulse lanzó 3 nuevos creativos en Meta Ads atacando a líderes en ${cleanNiche}`,
        sourceCompetitor: 'NovaPulse Ágil',
        message: 'Están usando videos testimoniales con ganchos comparativos directos sobre el alto costo de ApexFlow.',
        severity: 'high',
        suggestedReaction: 'Desplegar campaña en Google Search para capturar el tráfico de búsqueda comparativa.',
        isRead: false,
      },
      {
        id: 'alt-2',
        timestamp: 'Hace 18 minutos',
        type: 'opportunity',
        title: 'ApexFlow incrementó su puja de CPC un 28% en Google Search',
        sourceCompetitor: 'ApexFlow Growth',
        message: 'Oportunidad de capturar palabras clave de cola larga ("long-tail") a un 60% menos costo.',
        severity: 'medium',
        suggestedReaction: 'Activar campaña en términos específicos de nicho con intención de compra alta.',
        isRead: false,
      }
    ],
    chartData: [
      { competitor: 'ApexFlow Growth', marketShare: 36, adSpendScore: 88, featureSophistication: 92, priceIndex: 85, organicStrength: 90, sentimentScore: 78 },
      { competitor: 'NovaPulse Ágil', marketShare: 28, adSpendScore: 94, featureSophistication: 78, priceIndex: 55, organicStrength: 72, sentimentScore: 89 },
      { competitor: 'OmniScale Enterprise', marketShare: 20, adSpendScore: 45, featureSophistication: 88, priceIndex: 98, organicStrength: 81, sentimentScore: 65 },
      { competitor: 'KlaroLite Simple', marketShare: 16, adSpendScore: 72, featureSophistication: 45, priceIndex: 20, organicStrength: 52, sentimentScore: 74 },
    ],
    trendHistory: [
      { month: 'Mes -5', 'ApexFlow': 38, 'NovaPulse': 18, 'OmniScale': 22, 'KlaroLite': 8, 'Tendencia IA': 25 },
      { month: 'Mes -4', 'ApexFlow': 37, 'NovaPulse': 20, 'OmniScale': 21, 'KlaroLite': 9, 'Tendencia IA': 38 },
      { month: 'Mes -3', 'ApexFlow': 36, 'NovaPulse': 22, 'OmniScale': 20, 'KlaroLite': 10, 'Tendencia IA': 52 },
      { month: 'Mes -2', 'ApexFlow': 35, 'NovaPulse': 24, 'OmniScale': 20, 'KlaroLite': 11, 'Tendencia IA': 69 },
      { month: 'Mes -1', 'ApexFlow': 34, 'NovaPulse': 25, 'OmniScale': 19, 'KlaroLite': 12, 'Tendencia IA': 85 },
      { month: 'Actual', 'ApexFlow': 36, 'NovaPulse': 28, 'OmniScale': 20, 'KlaroLite': 16, 'Tendencia IA': 100 },
      { month: '+30d Proy.', 'ApexFlow': 34, 'NovaPulse': 30, 'OmniScale': 18, 'KlaroLite': 18, 'Tendencia IA': 125 },
      { month: '+60d Proy.', 'ApexFlow': 32, 'NovaPulse': 33, 'OmniScale': 17, 'KlaroLite': 19, 'Tendencia IA': 150 },
    ],
    unclaimedBlueOceans: [
      {
        gap: 'Onboarding autónomo asistido por IA en menos de 90 segundos',
        whyMissing: 'Los líderes dependen de llamadas de ventas obligatorias o manuales complejos.',
        howToCapitalize: 'Permite que el usuario configure su entorno en 1 clic sin fricción.',
      },
      {
        gap: 'Transparencia de precios radical y garantía sin preguntas',
        whyMissing: 'OmniScale y ApexFlow ocultan costos de implementación y extras.',
        howToCapitalize: 'Usa el lema "El único con precios 100% transparentes y sin letra chica".',
      }
    ],
    strategicPlaybook: [
      {
        phase: 'Fase 1: Asalto de Adquisición Rápida (Días 1-15)',
        action: 'Lanzar campañas en Google Search en keywords "Alternativa a [Competidor]" con ángulo de velocidad y soporte.',
        targetCompetitor: 'NovaPulse Ágil y ApexFlow Growth',
        expectedROI: '3.8x ROAS en los primeros 30 días',
      },
      {
        phase: 'Fase 2: Dominación en Meta Ads con UGC de Dolor (Días 15-30)',
        action: 'Desplegar variaciones de Reels mostrando el problema real que los software caros no resuelven.',
        targetCompetitor: 'ApexFlow Growth',
        expectedROI: '+45% aumento en tasa de clics (CTR)',
      }
    ]
  };
}
